chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"

urlpatterns = [
    path("room/<int:study_id>/create/", views.make_chat_room, name="make_chat_room"),
    # path("room/<int:room_id>/chat/", views.chat_room, name="chat_room"),
    path("room/<int:room_id>/chat/", views.ChatRoomView.as_view(), name="chat_room"),
    path("room/<int:room_id>/delete/", views.room_delete, name="room_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studies/", include("manager.urls", namespace="manager")),
    path("users/", include("user.urls")),
    path("", include("recruit.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("accounts/", include("allauth.urls")),
    path("video/", include("video.urls")),
    path("messages/", include("message.urls", namespace="message")),
    path("chat/", include("chat.urls")),
    path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from . import views


app_name = "manager"

urlpatterns = [
    path("", views.StudyView.as_view(), name="studies_list"),
    path("<int:pk>/", views.StudyDetailView.as_view(), name="study_detail"),
    path("<int:pk>/like/", views.studies_like_recruit, name="studies_like_recruit"),
    path(
        "<int:pk>/unlike/", views.studies_unlike_recruit, name="studies_unlike_recruit"
    ),
    path("<int:pk>/modify/", views.StudyModifyView.as_view(), name="study_modify"),
    path(
        "<int:pk>/recruting/", views.StudyRecrutingView.as_view(), name="study_recuting"
    ),
    path(
        "<int:pk>/inprogress/",
        views.StudyInProgressView.as_view(),
        name="study_inprogress",
    ),
    path("<int:pk>/done/", views.StudyDoneView.as_view(), name="study_done"),
    path("<int:pk>/finished/", views.StudyFinishView.as_view(), name="study_finished"),
    path("<int:pk>/leave/", views.StudyLeaveView.as_view(), name="study_leave"),
    path("<int:pk>/delete/", views.StudyDeleteView.as_view(), name="study_delete"),
    path(
        "<int:pk>/kickout/<int:member_id>/",
        views.StudyKickoutView.as_view(),
        name="study_kickout",
    ),
    path(
        "<int:pk>/task/create/",
        views.TaskCreateView.as_view(),
        name="task_create",
    ),
    path(
        "tasks/<int:pk>/modify/",
        views.TaskModifyView.as_view(),
        name="task_modify",
    ),
    path(
        "tasks/<int:pk>/complete/",
        views.TaskCompleteView.as_view(),
        name="task_complete",
    ),
    path(
        "tasks/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task_delete",
    ),
    path("tasks/<int:pk>/posts/new/", views.create_post_with_files, name="post_create"),
    path("tasks/<int:pk>/posts/", views.PostView.as_view(), name="post_list"),
    path("posts/<int:pk>/modify/", views.update_post_with_files, name="post_modify"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("posts/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
    path("files/<int:pk>/delete/", views.FileDeleteView.as_view(), name="file_delete"),
    path("files/<int:pk>/download/", views.download_s3_file, name="download_s3_file"),
]

recruit/urls.py
from django.urls import path

from recruit import views

app_name = "recruits"

urlpatterns = [
    path("", views.RecruitView.as_view(), name="index"),
    path("recruit/<int:pk>/like/", views.like_recruit, name="like_recruit"),
    path("recruit/<int:pk>/unlike/", views.unlike_recruit, name="unlike_recruit"),
    path(
        "recruits/<int:pk>/", views.RecruitDetailView.as_view(), name="recruit_detail"
    ),
    path(
        "recruits/<int:pk>/requests/",
        views.RequestView.as_view(),
        name="recruit_request",
    ),
    path(
        "registers/confirm/<int:pk>/",
        views.ConfirmRegisterView.as_view(),
        name="confirm_request",
    ),
    path(
        "registers/cancel/<int:pk>/",
        views.CancelRegisterView.as_view(),
        name="cancel_request",
    ),
    path("recruits/new/", views.RecruitCreateView.as_view(), name="create_recruit"),
    path(
        "recruits/<int:pk>/modify/",
        views.RecruitModifyView.as_view(),
        name="modify_recruit",
    ),
    path(
        "files/<int:file_pk>/delete/<int:recruit_pk>/",
        views.FileDeleteView.as_view(),
        name="file_delete",
    ),
    path(
        "recruits/<int:pk>/requests/<int:user_id>/reviews/",
        views.RequesterReviewView.as_view(),
        name="requester_review",
    ),
]

recruit/models.py
from django.contrib.auth.models import User
from django.db import models
from django_prometheus.models import ExportModelOperationsMixin
from taggit.managers import TaggableManager

from manager.models import File, Study


class Recruit(ExportModelOperationsMixin("recruit"), models.Model):
    study = models.OneToOneField(
        Study, on_delete=models.CASCADE, related_name="recruits"
    )
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="creator_recruits"
    )
    title = models.CharField(max_length=100)
    tags = TaggableManager()
    deadline = models.DateField()
    start = models.DateField()
    end = models.DateField()
    total_seats = models.IntegerField(default=1)
    members = models.ManyToManyField(User, related_name="members_recruits")
    target = models.TextField()
    process = models.TextField()
    info = models.TextField(null=True)
    like_users = models.ManyToManyField(User, related_name="likeusers_recruits")
    files = models.ManyToManyField(File, related_name="recruits", blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.creator}의 모집글 {self.title}"

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"]),
            models.Index(fields=["study"]),
        ]
        ordering = ["-created_at"]


class Register(ExportModelOperationsMixin("register"), models.Model):
    recruit = models.ForeignKey(
        Recruit, on_delete=models.CASCADE, related_name="registers"
    )
    requester = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="registers"
    )
    content = models.TextField()
    is_joined = models.BooleanField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.requester}의 {self.recruit}에 대한 신청"

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"]),
        ]
        ordering = ["-created_at"]

recruit/forms.py
from django import forms
from django.core.exceptions import ValidationError

from recruit.models import Register, Recruit


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, label="모집글", required=False)
    tag = forms.CharField(max_length=100, label="태그", required=False)


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = ["content"]


class RecruitForm(forms.ModelForm):
    start = forms.DateField(label="시작일", widget=forms.DateInput(attrs={"type": "date"}))
    end = forms.DateField(label="종료일", widget=forms.DateInput(attrs={"type": "date"}))
    deadline = forms.DateField(
        label="마감일", widget=forms.DateInput(attrs={"type": "date"})
    )
    total_seats = forms.IntegerField(initial=2, min_value=2, label="모집 인원")
    file = forms.FileField(required=False, label="파일")

    class Meta:
        model = Recruit
        fields = [
            "title",
            "tags",
            "deadline",
            "start",
            "end",
            "total_seats",
            "target",
            "process",
            "info",
            "file",
        ]

    def clean_file(self):
        file = self.cleaned_data.get("file")
        if file:
            if file.size > 3 * 1024 * 1024:  # 3MB
                raise ValidationError("Maximum File Size: 3MB")
        return file

templates/recruits/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
{% endblock style %}
{% block content %}
    <div class="flex h-full max-w-3xl px-8 mx-auto lg:max-w-5xl lg:px-0">
        <div class="flex flex-col flex-auto">
            <div class="flex-none pt-16 overflow-hidden md:mr-8">
                <div class="flex flex-col justify-between lg:flex-row">
                    <form method="get"
                          class="flex flex-col justify-between flex-auto lg:flex-row lg:pr-10">
                        <div class="flex flex-col flex-auto">
                            <h2 class="text-2xl text-neutral-500">스터디 검색</h2>
                            <label class="flex p-1 px-2 mt-2 border-b border-neutral-500 cursor-text">
                                <i class="fa-solid fa-magnifying-glass"></i>
                                <input type="text"
                                       name="query"
                                       maxlength="100"
                                       id="id_query"
                                       value="{{ query|default:''|safe }}"
                                       placeholder="키워드를 입력해주세요."
                                       class="flex w-full pl-2 bg-transparent outline-none placeholder-slate-400">
                                {% if query %}
                                    <a href="{% url 'recruits:index' %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             fill="none"
                                             viewBox="0 0 24 24"
                                             stroke-width="1.5"
                                             stroke="currentColor"
                                             class="w-5 h-5 hover:text-wanted-blue mt-[6px]">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                    </a>
                                {% endif %}
                            </label>
                        </div>
                        <div class="flex flex-col flex-auto mt-8 lg:mt-0 lg:pl-8">
                            <h2 class="text-2xl text-neutral-500">태그 필터</h2>
                            <label class="flex p-1 px-2 mt-2 border-b border-neutral-500 cursor-text">
                                <i class="fa-regular fa-tag"></i>
                                <input type="text"
                                       name="tag"
                                       maxlength="100"
                                       id="id_tag"
                                       value="{{ tag|default:''|safe }}"
                                       placeholder="태그를 입력해주세요."
                                       class="flex w-full pl-2 bg-transparent outline-none placeholder-slate-400">
                                {% if tag %}
                                    <a href="{% url 'recruits:index' %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             fill="none"
                                             viewBox="0 0 24 24"
                                             stroke-width="1.5"
                                             stroke="currentColor"
                                             class="w-5 h-5 hover:text-wanted-blue mt-[6px]">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                    </a>
                                {% endif %}
                            </label>
                        </div>
                        <input type="submit" hidden>
                    </form>
                    <div class="flex justify-end mt-8 lg:block lg:mt-0">
                        <a href="{% url 'recruits:create_recruit' %}">
                            <div class="px-2 py-1 text-white bg-neutral-600 hover:bg-neutral-700">
                                <span>모집하기</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <ul id="recruit-list"
                class="grid overflow-y-auto recruits {% if user.is_authenticated %}grid-cols-1 lg:grid-cols-2{% else %}grid-cols-2 lg:grid-cols-3{% endif %} gap-6 mt-8 md:pr-6">
                {% for recruit in recruits %}
                    <li class="px-6 py-4 border">
                        <a href="{% url 'recruits:recruit_detail' recruit.id %}">
                            <div class="w-full">
                                <h3 class="text-xl truncate">{{ recruit.title }}</h3>
                                <p class="pt-1">{{ recruit.creator }}</p>
                            </div>
                            <div class="flex justify-between pt-2 text-sm">
                                <span class="text-neutral-500">{{ recruit.deadline|date:'Y.m.d' }}</span>
                                <span>{{ recruit.members.count }}/{{ recruit.total_seats }}</span>
                            </div>
                        </a>
                        <ul class="flex flex-wrap pt-1">
                            {% for tag in recruit.tags.all %}
                                <li class="mb-2 mr-2 text-sm last:m-0">
                                    <a href="?tag={{ tag.name }}" class="px-2 bg-neutral-200">{{ tag.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                        <div class="pt-1">
                            <span class="text-sm">{{ recruit.like_users.count }}</span>
                            {% if recruit in liked_recruits %}
                                <a href="{% url 'recruits:unlike_recruit' recruit.pk %}">
                                    <i class="text-red-400 fa-solid fa-heart"></i>
                                </a>
                            {% else %}
                                <a href="{% url 'recruits:like_recruit' recruit.pk %}">
                                    <i class="fa-solid fa-heart"></i>
                                </a>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if user.is_authenticated %}
            <div id="sidebar"
                 class="flex-none hidden w-64 overflow-y-auto border-l border-r border-neutral-300 md:block">
                <div class="px-4 pt-20">
                    <div class="pb-8">
                        <h3 class="mb-2 text-xl font-bold">참여 중인 스터디</h3>
                        <hr class="border-neutral-300" />
                        {% if in_studies %}
                            <ul class="mt-2">
                                {% for study in in_studies %}
                                    <li class="pb-1 pl-2 mb-1 border-b border-neutral-200 last:border-none last:pb-0 last:mb-0">
                                        <a href="{% url 'manager:study_detail' study.id %}"
                                           class="block truncate">{{ study.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div>
                        <h3 class="pb-2 text-xl font-bold">좋아요 누른 스터디</h3>
                        <hr class="border-neutral-300" />
                        {% if liked_recruits %}
                            <ul class="mt-2">
                                {% for recruit in liked_recruits %}
                                    <li class="pb-1 pl-2 mb-1 border-b border-neutral-200 last:border-none last:pb-0 last:mb-0">
                                        <a href="{% url 'recruits:recruit_detail' recruit.id %}"
                                           class="block truncate">{{ recruit.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}
{% block script %}
    <script>
    document.addEventListener('DOMContentLoaded', (event) => {
            let page = 1;
            let emptyPage = false;
            let blockRequest = false;
            let lastScrollY = 0;
            let inputQuery = document.getElementById("id_query");
            let queryParameter = inputQuery.value;
            let recruits = document.querySelector(".recruits")

            recruits.addEventListener('scroll', function (e) {
                let currentScrollY = recruits.scrollTop;
                let margin = recruits.scrollHeight - recruits.clientHeight - 200;

                if (currentScrollY > lastScrollY && currentScrollY > margin && !emptyPage && !blockRequest) {
                    blockRequest = true;
                    page += 1;
                    let requestUrl = `?page=${page}`;
                    if (queryParameter) {
                        requestUrl += `&query=${queryParameter}`
                    }
                    fetch(requestUrl)
                        .then(response => response.text())
                        .then(html => {
                            let parser = new DOMParser();
                            let doc = parser.parseFromString(html, 'text/html');
                            let recruitContent = doc.querySelector(".recruits").innerHTML;

                            if (recruitContent === '') {
                                emptyPage = true;
                            } else {
                                recruits.insertAdjacentHTML('beforeend', recruitContent);
                                blockRequest = false;
                            }
                        });
                }
                lastScrollY = currentScrollY;
            });
        })
        let scrollEvent = new Event('scroll');
        document.querySelector(".recruits").dispatchEvent(scrollEvent);
    </script>
{% endblock script %}

templates/recruits/recruit_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="container md:max-w-3xl mx-auto pt-6">
        <h3 class="text-3xl">정말로 삭제하실건가요?</h3>
        <div class="flex pt-3">
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="bg-red-500 text-white p-1 px-2 rounded-md mr-3">삭제</button>
            </form>
            <a href="{% url 'manager:studies_list' %}"
               class="bg-neutral-300 p-1 px-2 rounded-md">취소</a>
        </div>
    </div>
{% endblock content %}

templates/recruits/recruit_form.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock style %}
{% block content %}
    <div class="mx-auto px-8 max-w-5xl pt-10 min-h-[calc(100%-68px)]">
        <form action=""
              method="post"
              enctype="multipart/form-data"
              class="pb-16 mt-10">
            {% if form.errors %}
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>
                                <div class="flex items-end justify-center min-h-full p-4 text-center sm:items-center sm:p-0">
                                    <div class="relative overflow-hidden text-left transition-all transform bg-white rounded-lg sm:my-3 sm:w-full sm:max-w-lg">
                                        <div class="px-4 pt-2 pb-1 bg-white">
                                            <div class="sm:flex sm:items-start">
                                                <div class="flex items-center justify-center flex-shrink-0 w-12 h-12 mx-auto bg-red-100 rounded-full sm:mx-0 sm:h-10 sm:w-10">
                                                    <svg class="w-6 h-6 text-red-600"
                                                         fill="none"
                                                         viewBox="0 0 24 24"
                                                         stroke-width="1.5"
                                                         stroke="currentColor"
                                                         aria-hidden="true">
                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z">
                                                        </path>
                                                    </svg>
                                                </div>
                                                <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                                                    <h3 class="text-base font-semibold leading-6 text-gray-900"
                                                        id="modal-title">{{ field.label }} 오류</h3>
                                                    <div class="mt-2">
                                                        <p class="text-sm text-gray-500">{{ field.label }}: {{ error }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
            {% csrf_token %}
            <input id="id_title"
                   type="text"
                   name="title"
                   maxlength="100"
                   value="{{ form.title.value|default:''|safe }}"
                   required
                   placeholder="Title"
                   class="w-full text-3xl font-bold outline-none placeholder-slate-400">
            <div class="mt-10">
                <p class="text-lg font-bold">태그</p>
                <hr class="my-2" />
                <i class="fa-solid fa-magnifying-glass"></i>
                <input id="tag"
                       type="text"
                       placeholder="태그를 입력해주세요."
                       oninput="search(this)"
                       class="px-2 py-1 outline-none bg-neutral-100">
                <div id="checkedbox" class="mt-4"></div>
                <div id="tagbox" class="mt-4"></div>
                <input id="id_tags"
                       type="text"
                       name="tags"
                       class="absolute outline-none opacity-0 cursor-default"
                       readonly
                       required>
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">마감일</p>
                <hr class="my-2" />
                <label for="id_deadline">
                    <input id="id_deadline"
                           type="date"
                           name="deadline"
                           value="{{ form.deadline.value|default:''|safe }}"
                           required
                           placeholder="모집 마감일 선택"
                           class="px-2 text-base text-center w-36 bg-neutral-100">
                </label>
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">기간</p>
                <hr class="my-2" />
                <input id="id_start"
                       type="date"
                       name="start"
                       value="{{ form.start.value|default:''|safe }}"
                       required=""
                       placeholder="시작일 선택"
                       class="px-2 text-base text-center w-28 bg-neutral-100">
                <span class="mx-4">~</span>
                <input id="id_end"
                       type="date"
                       name="end"
                       value="{{ form.end.value|default:''|safe }}"
                       required=""
                       placeholder="종료일 선택"
                       class="px-2 text-base text-center w-28 bg-neutral-100">
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">모집 인원</p>
                <hr class="my-2" />
                <input type="number"
                       min="2"
                       max="99"
                       name="total_seats"
                       value="{{ form.total_seats.value|default:''|safe }}"
                       required
                       id="id_total_seats"
                       class="w-16 px-2 rounded-sm outline-none bg-neutral-100">
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">모집 대상</p>
                <hr class="my-2" />
                <div class="w-full">
                    <textarea id="id_target"
                              name="target"
                              required
                              maxheight="200px"
                              placeholder="모집 대상을 입력해주세요."
                              class="w-full outline-none resize-none">{{ form.target.value|default:''|safe }}</textarea>
                </div>
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">진행 방식</p>
                <hr class="my-2" />
                <textarea id="id_process"
                          name="process"
                          required
                          maxheight="200px"
                          placeholder="진행 방식을 입력해주세요."
                          class="w-full outline-none resize-none">{{ form.process.value|default:''|safe }}</textarea>
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">추가 정보</p>
                <hr class="my-2" />
                <textarea id="id_info"
                          name="info"
                          required
                          maxheight="200px"
                          placeholder="추가 정보를 입력해주세요."
                          class="w-full outline-none resize-none">{{ form.info.value|default:''|safe }}</textarea>
            </div>
            <div class="mt-10">
                <p class="text-lg font-bold">파일 등록</p>
                <hr class="my-2" />
                {% if not recruit.files.exists %}
                    <input id="id_file"
                           type="file"
                           name="file"
                           class="cursor-pointer file:border-none file:bg-neutral-200 file:hover:bg-neutral-300 file:rounded-sm">
                {% else %}
                    {% with recruit_file=recruit.files.first %}
                        <p class="flex justify-between mt-4">
                            <a href="{{ recruit_file.url }}">{{ recruit_file.name }}</a>
                            <a href="{% url 'recruits:file_delete' file_pk=recruit_file.id recruit_pk=recruit.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 20 20"
                                     fill="currentColor"
                                     class="w-4 h-4 cursor-pointer fill-slate-500 remove-file"
                                     title="파일 삭제">
                                    <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z" clip-rule="evenodd" class="remove-file" />
                                </svg>
                            </a>
                        </p>
                    {% endwith %}
                {% endif %}
            </div>
            <input type="submit" value="Create" hidden>
        </form>
    </div>
    <div class="sticky bottom-0 h-[68px] bg-white border-t border-neutral-300">
        <div class="max-w-5xl mx-auto">
            <div class="h-16">
                <div class="flex justify-between h-full">
                    <div class="flex flex-row self-center info">
                        <p class="hidden font-bold sm:flex">{% now "Y년 m월 d일" %} : &nbsp;</p>
                        <p class="font-bold">
                            {{ user }}님의 게시글
                            {% if view_type == 'create' %}
                                작성
                            {% else %}
                                수정
                            {% endif %}
                        </p>
                    </div>
                    <button id="submit"
                            class="self-center px-5 py-3 text-white bg-neutral-600 hover:bg-neutral-700">작성 완료</button>
                </div>
            </div>
        </div>
    </div>
    <div id="tag-list" class="hidden">
        {% for tag in tags %}<data>{{ tag }}</data>{% endfor %}
    </div>
    <div id="selected-tags" class="hidden">{{ form.tags }}</div>
{% endblock content %}
{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script type="text/javascript" src="{% static 'js/resizeTextarea.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tagList.js' %}"></script>
    <script>
        flatpickr('#id_deadline', {
            dateFormat: "Y-m-d",
          });
          
          flatpickr('#id_start', {
            dateFormat: "Y-m-d",
          });
          
          flatpickr('#id_end', {
            dateFormat: "Y-m-d",
          });
    </script>
{% endblock script %}