chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"

urlpatterns = [
    path("room/<int:study_id>/create/", views.make_chat_room, name="make_chat_room"),
    # path("room/<int:room_id>/chat/", views.chat_room, name="chat_room"),
    path("room/<int:room_id>/chat/", views.ChatRoomView.as_view(), name="chat_room"),
    path("room/<int:room_id>/delete/", views.room_delete, name="room_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studies/", include("manager.urls", namespace="manager")),
    path("users/", include("user.urls")),
    path("", include("recruit.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("accounts/", include("allauth.urls")),
    path("video/", include("video.urls")),
    path("messages/", include("message.urls", namespace="message")),
    path("chat/", include("chat.urls")),
    path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from . import views


app_name = "manager"

urlpatterns = [
    path("", views.StudyView.as_view(), name="studies_list"),
    path("<int:pk>/", views.StudyDetailView.as_view(), name="study_detail"),
    path("<int:pk>/like/", views.studies_like_recruit, name="studies_like_recruit"),
    path(
        "<int:pk>/unlike/", views.studies_unlike_recruit, name="studies_unlike_recruit"
    ),
    path("<int:pk>/modify/", views.StudyModifyView.as_view(), name="study_modify"),
    path(
        "<int:pk>/recruting/", views.StudyRecrutingView.as_view(), name="study_recuting"
    ),
    path(
        "<int:pk>/inprogress/",
        views.StudyInProgressView.as_view(),
        name="study_inprogress",
    ),
    path("<int:pk>/done/", views.StudyDoneView.as_view(), name="study_done"),
    path("<int:pk>/finished/", views.StudyFinishView.as_view(), name="study_finished"),
    path("<int:pk>/leave/", views.StudyLeaveView.as_view(), name="study_leave"),
    path("<int:pk>/delete/", views.StudyDeleteView.as_view(), name="study_delete"),
    path(
        "<int:pk>/kickout/<int:member_id>/",
        views.StudyKickoutView.as_view(),
        name="study_kickout",
    ),
    path(
        "<int:pk>/task/create/",
        views.TaskCreateView.as_view(),
        name="task_create",
    ),
    path(
        "tasks/<int:pk>/modify/",
        views.TaskModifyView.as_view(),
        name="task_modify",
    ),
    path(
        "tasks/<int:pk>/complete/",
        views.TaskCompleteView.as_view(),
        name="task_complete",
    ),
    path(
        "tasks/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task_delete",
    ),
    path("tasks/<int:pk>/posts/new/", views.create_post_with_files, name="post_create"),
    path("tasks/<int:pk>/posts/", views.PostView.as_view(), name="post_list"),
    path("posts/<int:pk>/modify/", views.update_post_with_files, name="post_modify"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("posts/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
    path("files/<int:pk>/delete/", views.FileDeleteView.as_view(), name="file_delete"),
    path("files/<int:pk>/download/", views.download_s3_file, name="download_s3_file"),
]

manager/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import modelformset_factory

from markdownx.fields import MarkdownxFormField
from markdownx.widgets import MarkdownxWidget

from .models import File, Post, Study, Task


class StudyForm(forms.ModelForm):
    start = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    end = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Study
        fields = ["title", "start", "end", "process", "info"]

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get("start")
        end = cleaned_data.get("end")

        if start and end:
            if start > end:
                raise ValidationError("시작일은 종료일보다 뒤에 있을 수 없습니다.")

        return cleaned_data


class TaskForm(forms.ModelForm):
    start = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "w-28 text-center bg-neutral-100 px-2 rounded-md",
                "placeholder": "시작일 선택",
            }
        )
    )
    end = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "w-28 text-center bg-neutral-100 px-2 rounded-md",
                "placeholder": "종료일 선택",
            }
        )
    )

    class Meta:
        model = Task
        fields = ["title", "description", "start", "end"]


class FileUploadForm(forms.ModelForm):
    file = forms.FileField(
        label="",
        required=False,
        widget=forms.FileInput(
            attrs={
                "class": "file:border-none file:bg-neutral-200 file:hover:bg-neutral-300 file:rounded-sm cursor-pointer"
            }
        ),
    )

    class Meta:
        model = File
        fields = ("file",)

    def clean_file(self):
        file = self.cleaned_data.get("file")
        if file:
            if file.size > 3 * 1024 * 1024:  # 3MB
                raise ValidationError("Maximum File Size: 3MB")
        return file


FileUploadFormSet = modelformset_factory(File, form=FileUploadForm, extra=1, max_num=5)


class FileForm(forms.ModelForm):
    checkbox = forms.BooleanField(
        label="", required=False, widget=forms.CheckboxInput(), initial=True
    )
    url = forms.URLField(
        label="",
        disabled=True,
        required=False,
        widget=forms.FileInput(
            attrs={
                "class": "file:border-none file:bg-neutral-200 file:hover:bg-neutral-300 file:rounded-sm cursor-pointer"
            }
        ),
    )

    class Meta:
        model = File
        fields = ("url", "checkbox")


class PostActionForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "w-full",
                "placeholder": "제목을 입력해주세요.",
            }
        )
    )
    content = MarkdownxFormField(
        required=False,
        widget=MarkdownxWidget(
            attrs={
                "style": "display: none",
            }
        ),
    )

    class Meta:
        model = Post
        fields = (
            "title",
            "content",
        )

recruit/forms.py
from django import forms
from django.core.exceptions import ValidationError

from recruit.models import Register, Recruit


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, label="모집글", required=False)
    tag = forms.CharField(max_length=100, label="태그", required=False)


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = ["content"]


class RecruitForm(forms.ModelForm):
    start = forms.DateField(label="시작일", widget=forms.DateInput(attrs={"type": "date"}))
    end = forms.DateField(label="종료일", widget=forms.DateInput(attrs={"type": "date"}))
    deadline = forms.DateField(
        label="마감일", widget=forms.DateInput(attrs={"type": "date"})
    )
    total_seats = forms.IntegerField(initial=2, min_value=2, label="모집 인원")
    file = forms.FileField(required=False, label="파일")

    class Meta:
        model = Recruit
        fields = [
            "title",
            "tags",
            "deadline",
            "start",
            "end",
            "total_seats",
            "target",
            "process",
            "info",
            "file",
        ]

    def clean_file(self):
        file = self.cleaned_data.get("file")
        if file:
            if file.size > 3 * 1024 * 1024:  # 3MB
                raise ValidationError("Maximum File Size: 3MB")
        return file

templates/studies/tasks/board.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
{% endblock style %}
{% block content %}
    <div class="flex flex-col items-center max-w-5xl mx-auto">
        <div class="flex flex-col items-start xl:w-full lg:w-[768px] sm:w-3/4 w-4/5 mt-14 task">
            <div class="text-5xl font-bold truncate title xl:w-full lg:w-[768px] sm:w-3/4 w-4/5">{{ task.title }}</div>
            <div class="mt-10 mb-10 text-3xl truncate description xl:w-full lg:w-[768px] sm:w-3/4 w-4/5">
                {{ task.description }}
            </div>
        </div>
        <div class="flex my-4 items-center justify-between xl:w-full lg:w-[768px] sm:w-3/4 w-4/5 header">
            <div class="flex flex-row search">
                <form method="get" class="block mr-3 search">
                    <label class="px-4 py-2 border-b border-neutral-500 cursor-text">
                        <i class="fa-solid fa-magnifying-glass"></i>
                        <input type="text"
                               name="query"
                               maxlength="30"
                               id="id_query"
                               value="{{ query|default:''|safe }}"
                               placeholder="키워드 검색"
                               class="pl-2 bg-transparent outline-none placeholder-slate-400 search xl:w-[300px] lg:w-[200px] sm:w-[150px] w-[100px]"
                               value="{{ query }}">
                    </label>
                    <button type="submit" hidden>검색</button>
                </form>
                {% if query %}
                    <a href="{% url 'manager:post_list' task.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="w-5 h-5 hover:text-wanted-blue mt-[6px]">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </a>
                {% endif %}
            </div>
            <div class="flex item-center btn">
                <button class="px-3 mr-4 create"
                        onclick="location.href='{% url 'manager:post_create' task.id %}'">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:scale-125 hover:text-wanted-cyan">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                    </svg>
                </button>
                <button class="px-3 study"
                        onclick="location.href='{% url 'manager:study_detail' task.study.id %}'">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:scale-125 hover:text-wanted-blue">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                    </svg>
                </button>
            </div>
        </div>
        <div class="xl:w-full lg:w-[768px] sm:w-3/4 w-4/5 border-y-2 border-neutral-500">
            <div class="thead">
                <div class="flex flex-row items-center h-12 text-lg border-b border-neutral-500 bg-neutral-100">
                    <div class="mx-2 font-semibold text-center basis-1/6 td">날짜</div>
                    <div class="mx-2 font-semibold text-center basis-3/6 td">제목</div>
                    <div class="mx-2 font-semibold text-center basis-1/6 td">작성자</div>
                    <div class="hidden mx-2 font-semibold text-center basis-1/6 sm:block td">첨부파일</div>
                </div>
            </div>
            <div class="overflow-y-auto h-[500px] tbody" id="post-list">
                {% for post in posts %}
                    <div class="flex flex-row items-center h-10 text-sm border-y border-neutral-100 hover:bg-neutral-100/75">
                        <div class="mx-2 text-center basis-1/6 td">{{ post.created_at|date:"Y.m.d" }}</div>
                        <div class="mx-2 underline truncate basis-3/6 td hover:text-wanted-indigo">
                            <a href="{% url 'manager:post_detail' post.id %}">{{ post.title }}</a>
                        </div>
                        <div class="mx-2 text-center basis-1/6 td">{{ post.author.username }}</div>
                        <div class="hidden mx-2 text-center truncate basis-1/6 sm:block td">
                            {% if post.files.exists %}
                                <a href="{% url 'manager:download_s3_file' post.files.last.id %}"
                                   class="text-xs underline text-real-blue"
                                   download>{{ post.files.last.get_file_name }}</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            let page = 1;
            let emptyPage = false;
            let blockRequest = false;
            let lastScrollY = 0;
            let inputQuery = document.getElementById("id_query");
            let queryParameter = inputQuery.value;
            let tbody = document.querySelector(".tbody");

            tbody.addEventListener('scroll', function (e) {
                let currentScrollY = tbody.scrollTop;
                let margin = tbody.scrollHeight - tbody.clientHeight - 300;
                if (currentScrollY > lastScrollY && currentScrollY > margin && !emptyPage && !blockRequest) {
                    blockRequest = true;
                    page += 1;
                    let requestUrl = `?page=${page}`;
                    if (queryParameter) {
                        requestUrl += `&query=${queryParameter}`
                    }
                    fetch(requestUrl)
                        .then(response => response.text())
                        .then(html => {
                            let parser = new DOMParser();
                            let doc = parser.parseFromString(html, 'text/html');
                            let tbodyContent = doc.querySelector(".tbody").innerHTML;
                            if (tbodyContent === '') {
                                emptyPage = true;
                            } else {
                                tbody.insertAdjacentHTML('beforeend', tbodyContent);
                                blockRequest = false;
                            }
                        });
                }
                lastScrollY = currentScrollY;
            });
        })

        let scrollEvent = new Event('scroll');
        document.querySelector(".tbody").dispatchEvent(scrollEvent); 
    </script>
{% endblock script %}

templates/studies/tasks/create.html
<form action="{% url 'manager:task_create' study.id %}"
      method="post"
      class="p-1 mt-5 border-2 border-solid">
    <div class="flex flex-col">
        {% csrf_token %}
        <div class="flex flex-row mt-1 task-title">
            <input class="outline-none sm:w-1/2"
                   type="{{ task_form.title.widget.input_type }}"
                   placeholder="{{ task_form.title.label }}"
                   name="{{ task_form.title.name }}">
            <div class="sm:inline date">{{ task_form.start }} ~ {{ task_form.end }}</div>
            <button type="submit"
                    class="self-start w-5 h-5 ml-auto transition-all hover:scale-125 text-emerald-500">
                <i class="fa-solid fa-plus"></i>
            </button>
        </div>
    </div>
    <input class="w-full h-8 outline-none"
           type="{{ task_form.description.widget.input_type }}"
           placeholder="{{ task_form.description.label }}"
           name="{{ task_form.description.name }}">
    {% if messages %}
        {% for message in messages %}<div class="text-red-600">{{ message }}</div>{% endfor %}
    {% endif %}
</form>

templates/studies/tasks/modify.html
{% extends "base.html" %}
{% block style %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock style %}
{% block content %}
    <div class="mx-auto max-w-5xl pt-10 min-h-[calc(100%-68px)]">
        <form method="post">
            <div class="flex flex-col">
                <input class="w-full text-3xl font-bold outline-none placeholder-slate-400"
                       type="{{ form.title.widget.input_type }}"
                       placeholder="{{ form.title.label }}"
                       name="{{ form.title.name }}"
                       value="{{ form.title.value }}">
                <p class="text-lg font-bold mt-10">기간</p>
                <hr class="my-2" />
                <div class="sm:inline date">{{ form.start }} ~ {{ form.end }}</div>
                {% if messages %}
                    {% for message in messages %}<div class="text-red-600">{{ message }}</div>{% endfor %}
                {% endif %}
                <p class="text-lg font-bold mt-10">설명</p>
                <hr class="my-2" />
                <input class="w-full outline-none"
                       type="{{ form.description.widget.input_type }}"
                       placeholder="{{ form.description.label }}"
                       name="{{ form.description.name }}"
                       value="{{ form.description.value }}">
                {% csrf_token %}
                <div class="flex justify-between h-full">
                    <div class="opacity-0">empty element</div>
                    <div class="cursor-pointer self-center mt-4 px-3 py-2 text-white rounded-md bg-neutral-600 hover:bg-neutral-700">
                        <input class="cursor-pointer" type="submit" value="수정 완료">
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}
{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr('#id_start', {
            dateFormat: "Y-m-d",
        });

        flatpickr('#id_end', {
            dateFormat: "Y-m-d",
        });
    </script>
{% endblock script %}