chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"

urlpatterns = [
    path("room/<int:study_id>/create/", views.make_chat_room, name="make_chat_room"),
    # path("room/<int:room_id>/chat/", views.chat_room, name="chat_room"),
    path("room/<int:room_id>/chat/", views.ChatRoomView.as_view(), name="chat_room"),
    path("room/<int:room_id>/delete/", views.room_delete, name="room_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studies/", include("manager.urls", namespace="manager")),
    path("users/", include("user.urls")),
    path("", include("recruit.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("accounts/", include("allauth.urls")),
    path("video/", include("video.urls")),
    path("messages/", include("message.urls", namespace="message")),
    path("chat/", include("chat.urls")),
    path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from . import views


app_name = "manager"

urlpatterns = [
    path("", views.StudyView.as_view(), name="studies_list"),
    path("<int:pk>/", views.StudyDetailView.as_view(), name="study_detail"),
    path("<int:pk>/like/", views.studies_like_recruit, name="studies_like_recruit"),
    path(
        "<int:pk>/unlike/", views.studies_unlike_recruit, name="studies_unlike_recruit"
    ),
    path("<int:pk>/modify/", views.StudyModifyView.as_view(), name="study_modify"),
    path(
        "<int:pk>/recruting/", views.StudyRecrutingView.as_view(), name="study_recuting"
    ),
    path(
        "<int:pk>/inprogress/",
        views.StudyInProgressView.as_view(),
        name="study_inprogress",
    ),
    path("<int:pk>/done/", views.StudyDoneView.as_view(), name="study_done"),
    path("<int:pk>/finished/", views.StudyFinishView.as_view(), name="study_finished"),
    path("<int:pk>/leave/", views.StudyLeaveView.as_view(), name="study_leave"),
    path("<int:pk>/delete/", views.StudyDeleteView.as_view(), name="study_delete"),
    path(
        "<int:pk>/kickout/<int:member_id>/",
        views.StudyKickoutView.as_view(),
        name="study_kickout",
    ),
    path(
        "<int:pk>/task/create/",
        views.TaskCreateView.as_view(),
        name="task_create",
    ),
    path(
        "tasks/<int:pk>/modify/",
        views.TaskModifyView.as_view(),
        name="task_modify",
    ),
    path(
        "tasks/<int:pk>/complete/",
        views.TaskCompleteView.as_view(),
        name="task_complete",
    ),
    path(
        "tasks/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task_delete",
    ),
    path("tasks/<int:pk>/posts/new/", views.create_post_with_files, name="post_create"),
    path("tasks/<int:pk>/posts/", views.PostView.as_view(), name="post_list"),
    path("posts/<int:pk>/modify/", views.update_post_with_files, name="post_modify"),
    path("posts/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("posts/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
    path("files/<int:pk>/delete/", views.FileDeleteView.as_view(), name="file_delete"),
    path("files/<int:pk>/download/", views.download_s3_file, name="download_s3_file"),
]

message/urls.py
from django.urls import path

from . import views

app_name = "message"
urlpatterns = [
    path(
        "send/<int:user_id>/",
        views.MessageSendTargetView.as_view(),
        name="send_message_target",
    ),
    path("<int:pk>/read/", views.MessageReadView.as_view(), name="read_message"),
    path("<int:pk>/delete/", views.MessageDeleteView.as_view(), name="delete_message"),
    path("list/", views.MessageListView.as_view(), name="list_messages"),
    path("notices/", views.NoticeListView.as_view(), name="list_notices"),
    path(
        "notice/<int:pk>/delete/",
        views.NoticeDeleteView.as_view(),
        name="notice_delete",
    ),
]

recruit/urls.py
from django.urls import path

from recruit import views

app_name = "recruits"

urlpatterns = [
    path("", views.RecruitView.as_view(), name="index"),
    path("recruit/<int:pk>/like/", views.like_recruit, name="like_recruit"),
    path("recruit/<int:pk>/unlike/", views.unlike_recruit, name="unlike_recruit"),
    path(
        "recruits/<int:pk>/", views.RecruitDetailView.as_view(), name="recruit_detail"
    ),
    path(
        "recruits/<int:pk>/requests/",
        views.RequestView.as_view(),
        name="recruit_request",
    ),
    path(
        "registers/confirm/<int:pk>/",
        views.ConfirmRegisterView.as_view(),
        name="confirm_request",
    ),
    path(
        "registers/cancel/<int:pk>/",
        views.CancelRegisterView.as_view(),
        name="cancel_request",
    ),
    path("recruits/new/", views.RecruitCreateView.as_view(), name="create_recruit"),
    path(
        "recruits/<int:pk>/modify/",
        views.RecruitModifyView.as_view(),
        name="modify_recruit",
    ),
    path(
        "files/<int:file_pk>/delete/<int:recruit_pk>/",
        views.FileDeleteView.as_view(),
        name="file_delete",
    ),
    path(
        "recruits/<int:pk>/requests/<int:user_id>/reviews/",
        views.RequesterReviewView.as_view(),
        name="requester_review",
    ),
]

user/urls.py
from django.urls import path
from user import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("logout/", views.logout, name="logout"),
    path("info/", views.MyHistoryView.as_view(), name="info"),
    path("social_signup/", views.UserSocialSignupView.as_view(), name="social_signup"),
    path("write_review/<int:pk>/", views.write_review, name="write_review"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="study on">
        <meta name="keywords" content="study, recruit, plan, todo">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Study On</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <div class="h-full">
            <div class="fixed w-full h-[60px] border-b border-neutral-300 bg-[rgba(255,255,255,.88)] backdrop-blur-xl backdrop-saturate-150 z-50 header">
                <div class="flex items-center h-full max-w-5xl px-5 mx-auto mx-2xl:px-0">
                    <a href="{% url 'recruits:index' %}" class="flex">
                        <h1 class="self-center text-lg font-bold text-cyan-700">StudyOn</h1>
                    </a>
                    <div id="notice" class="fixed inset-x-0 top-[10px] flex justify-center"></div>
                    <div class="flex h-full ml-auto text-base">
                        {% if user.is_authenticated %}
                            <div class="flex items-center font-bold">
                                <a href="{% url 'message:list_notices' %}"
                                   target="_blank"
                                   onclick="return openPopup(this.href)">알림</a>
                                <span id="recent_notice" class="pt-1 text-red-400 place-self-start">
                                    {% if recent_notice.user == user %}•{% endif %}
                                </span>
                            </div>
                            <div class="flex items-center pl-6 font-bold">
                                <a href="{% url 'message:list_messages' %}"
                                   target="_blank"
                                   onclick="return openPopup(this.href)">메세지</a>
                                <span id="recent_message" class="pt-1 text-red-400 place-self-start">
                                    {% if not recent_message.read_at and recent_message.receiver == user %}•{% endif %}
                                </span>
                            </div>
                            <div class="flex items-center pl-6 font-bold">
                                <a href={% url 'users:info' %}>내 정보</a>
                            </div>
                            <div class="flex items-center pl-6 font-bold">
                                <a href={% url 'manager:studies_list' %}>스터디 관리</a>
                            </div>
                            <div class="flex items-center pl-6 font-bold">
                                <a href={% url 'users:logout' %}>로그아웃</a>
                            </div>
                        {% else %}
                            <div class="flex items-center pl-6 font-bold">
                                <a href={% url 'users:login' %}>로그인</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="h-[60px]"></div>
            <div class="h-[calc(100%-60px)]" id="body-content">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </body>
    <script>
        var href = document.location.href; // 전체 url
        var protocol = window.location.protocol; // http: or https:
        const wsProtocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
        var host = window.location.host; // 호스트 네임 ex) 127.0.0.1 , localhost
        var link = href.replace(protocol+"//","").replace(host,"");
        var notice_socket = new WebSocket(wsProtocol + host + "/ws/notice/");

        notice_socket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const notice = document.getElementById("notice");
            const recent_notice = document.getElementById("recent_notice");
            const recent_message = document.getElementById("recent_message");
            if (data.receiver_id == {{ user.id }}) {
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";
                recent_message.innerHTML = "•";

                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
            if (data.user_id == {{ user.id }}) {
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";
                recent_notice.innerHTML = "•";
                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
            if ( data.user_ids.includes({{ user.id }})){
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";
                recent_notice.innerHTML = "•";

                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
        };

        function openPopup(url) {
            window.open(url, '_blank', 'width=600,height=700,scrollbars=yes');
            return false;
        }

        {% block websocket %}
        {% endblock websocket %}
    </script>
    {% block include_js %}
    {% endblock include_js %}
    {% block script %}
    {% endblock script %}
</html>

templates/popup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="study on">
        <meta name="keywords" content="study, recruit, plan, todo">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Study On</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <div class="h-full">
            <div class="fixed w-full h-[60px] border-b border-neutral-300 bg-[rgba(255,255,255,.88)] backdrop-blur-xl backdrop-saturate-150 z-50 header">
                <div class="flex items-center w-4/5 h-full max-w-5xl px-5 mx-auto xl:w-full mx-2xl:px-0">
                    <h1 class="self-center text-lg font-bold text-cyan-700">StudyOn</h1>
                    <div id="notice" class="fixed inset-x-0 top-[10px] flex justify-center"></div>
                    <div class="flex h-full ml-auto text-base">
                        {% if user.is_authenticated %}
                            <div class="flex items-center font-bold">
                                <a href="{% url 'message:list_notices' %}">알림</a>
                                <span id="recent_notice" class="pt-1 text-red-400 place-self-start">
                                    {% if recent_notice.user == user %}•{% endif %}
                                </span>
                            </div>
                            <div class="flex items-center pl-6 font-bold">
                                <a href="{% url 'message:list_messages' %}">메세지</a>
                                <span id="recent_message" class="pt-1 text-red-400 place-self-start">
                                    {% if not recent_message.read_at and recent_message.receiver == user %}•{% endif %}
                                </span>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="h-[60px]"></div>
            <div class="h-[calc(100%-60px)] p-10" id="body-content">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </body>
    <script>
        var href = document.location.href; // 전체 url
        var protocol = window.location.protocol; // http: or https:
        const wsProtocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
        var host = window.location.host; // 호스트 네임 ex) 127.0.0.1 , localhost
        var link = href.replace(protocol+"//","").replace(host,"");
        var notice_socket = new WebSocket(wsProtocol + host + "/ws/notice/");

        notice_socket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const notice = document.getElementById("notice");
            const recent_notice = document.getElementById("recent_notice");
            const recent_message = document.getElementById("recent_message");
            if (data.receiver_id == {{ user.id }}) {
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";
                recent_message.innerHTML = "•";

                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
            if (data.user_id == {{ user.id }}) {
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";
                recent_notice.innerHTML = "•";
                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
            if ( data.user_ids.includes({{ user.id }})){
                notice.innerHTML = "<p class=\"leading-10 bg-neutral-100 px-2\">" + data.content + "</p>";

                setTimeout(function () {
                notice.innerHTML = '' ;
            }, 3000);
            };
        };

        function openPopup(url) {
            window.open(url, '_blank', 'width=600,height=600,scrollbars=yes');
            return false;
        }

        {% block websocket %}
        {% endblock websocket %}
    </script>
    {% block include_js %}
    {% endblock include_js %}
    {% block script %}
    {% endblock script %}
</html>