chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"

urlpatterns = [
    path("room/<int:study_id>/create/", views.make_chat_room, name="make_chat_room"),
    # path("room/<int:room_id>/chat/", views.chat_room, name="chat_room"),
    path("room/<int:room_id>/chat/", views.ChatRoomView.as_view(), name="chat_room"),
    path("room/<int:room_id>/delete/", views.room_delete, name="room_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studies/", include("manager.urls", namespace="manager")),
    path("users/", include("user.urls")),
    path("", include("recruit.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("accounts/", include("allauth.urls")),
    path("video/", include("video.urls")),
    path("messages/", include("message.urls", namespace="message")),
    path("chat/", include("chat.urls")),
    path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

message/urls.py
from django.urls import path

from . import views

app_name = "message"
urlpatterns = [
    path(
        "send/<int:user_id>/",
        views.MessageSendTargetView.as_view(),
        name="send_message_target",
    ),
    path("<int:pk>/read/", views.MessageReadView.as_view(), name="read_message"),
    path("<int:pk>/delete/", views.MessageDeleteView.as_view(), name="delete_message"),
    path("list/", views.MessageListView.as_view(), name="list_messages"),
    path("notices/", views.NoticeListView.as_view(), name="list_notices"),
    path(
        "notice/<int:pk>/delete/",
        views.NoticeDeleteView.as_view(),
        name="notice_delete",
    ),
]

message/models.py
from django.contrib.auth.models import User
from django.db import models
from django_prometheus.models import ExportModelOperationsMixin


class Message(ExportModelOperationsMixin("message"), models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="senders")
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="receivers"
    )
    title = models.CharField(max_length=50)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"]),
            models.Index(fields=["sender"]),
            models.Index(fields=["receiver"]),
        ]
        ordering = ["-created_at"]


class Notice(ExportModelOperationsMixin("notice"), models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notices")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"]),
            models.Index(fields=["user"]),
        ]
        ordering = ["-created_at"]

message/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View, DetailView, ListView
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.models import User
from message.permissions import MessageAccessMixin, MessageSendMixin, NoticeAccessMixin
from .models import Message, Notice


class NoticeListView(LoginRequiredMixin, ListView):
    model = Notice
    template_name = "messages/notice_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["notices"] = Notice.objects.filter(user=self.request.user)
        return context


class NoticeDeleteView(NoticeAccessMixin, View):
    def get(self, request, pk):
        return redirect("message:list_notices")

    def post(self, request, pk):
        notice = get_object_or_404(Notice, id=pk, user=request.user)
        notice.delete()
        return redirect("message:list_notices")


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = "messages/message_list.html"
    context_object_name = "messages"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset().filter(receiver=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        ...
        page = context["page_obj"]
        paginator = page.paginator
        pagelist = paginator.get_elided_page_range(
            page.number, on_each_side=3, on_ends=0
        )
        context["pagelist"] = pagelist
        ...
        return context


class MessageSendTargetView(MessageSendMixin, View):
    def get(self, request, user_id):
        receiver = get_object_or_404(User, id=user_id)
        return render(
            request,
            "messages/send_message_target.html",
            {"receiver": receiver},
        )

    def post(self, request, user_id):
        receiver = get_object_or_404(User, id=user_id)
        sender = request.user
        title = request.POST["title"]
        content = request.POST["content"]

        Message.objects.create(
            sender=sender, receiver=receiver, title=title, content=content
        )

        return redirect("message:list_messages")


class MessageReadView(MessageAccessMixin, DetailView):
    model = Message
    template_name = "messages/read_message.html"
    context_object_name = "message"

    def dispatch(self, request, *args, **kwargs):
        message = get_object_or_404(Message, id=kwargs["pk"])
        if message.receiver == request.user:
            message.read_at = timezone.now()
            message.save()
        return super().dispatch(request, *args, **kwargs)


class MessageDeleteView(MessageAccessMixin, View):
    def post(self, request, pk):
        message = get_object_or_404(Message, id=pk)

        try:
            message.delete()
            return redirect("message:list_messages")
        except Exception as e:
            return HttpResponse(str(e))

templates/messages/message_list.html
{% extends "popup.html" %}
{% load static %}
{% block style %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/regular.css' %}"
          rel="stylesheet"
          type="text/css">
{% endblock style %}
{% block content %}
    <div class="w-full h-full max-w-5xl mx-auto">
        <div class="flex justify-between w-4/5 mx-auto mb-5 xl:w-full send-msg">
            <div class="col-span-8 text-3xl font-semibold title">메세지 목록</div>
            <div class="flex">
                <a href="#" onClick="location.reload();" class="block mr-8">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1"
                         stroke="currentColor"
                         class="inline w-5 h-5 text-[#373737] hover:text-wanted-cyan mt-[8px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" class="mt-[8px]" />
                    </svg>
                </a>
                <a href="#" class="block" onclick="window.close();">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:text-wanted-blue mt-[6px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </a>
            </div>
        </div>
        <div class="flex justify-end w-4/5 mx-auto mb-5 text-xs xl:w-full">확인한 메세지는 30일 뒤 자동 삭제됩니다.</div>
        <div class="flex justify-center w-4/5 mx-auto mb-7 pagination xl:w-full">
            {% if page_obj.has_previous %}
                <div class="mx-2 mt-1 page-item">
                    <a class="page-link hover:text-wanted-blue hover:underline"
                       href="?page={{ page_obj.previous_page_number }}">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
                        </svg>
                    </a>
                </div>
            {% else %}
                <div class="mx-2 page-item disabled:">&nbsp;</div>
            {% endif %}
            {% for index in pagelist %}
                {% if index == page_obj.number %}
                    <div class="mx-2 page-item">
                        <span class="page-link text-wanted-cyan">{{ index }}</span>
                    </div>
                {% else %}
                    <div class="mx-2 page-item">
                        <a class="page-link hover:text-wanted-blue hover:underline"
                           href="?page={{ index }}">{{ index }}</a>
                    </div>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <div class="mx-2 mt-1 page-item">
                    <a class="page-link hover:text-wanted-blue hover:underline"
                       href="?page={{ page_obj.next_page_number }}">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                        </svg>
                    </a>
                </div>
            {% else %}
                <div class="mx-2 page-item disabled">&nbsp;</div>
            {% endif %}
        </div>
        {% for message in messages %}
            <div class="flex my-4 max-w-[80%] mx-auto justify-center rounded-md bg-neutral-100">
                <div class="flex flex-row justify-between w-full px-2 text-lg truncate ">
                    <a class="block mr-6 underline truncate hover:text-neutral-400"
                       href="{% url "message:read_message" message.id %}">{{ message }}</a>
                    <div class="self-center text-xs">{{ message.created_at|date:"n/j G:i" }}</div>
                </div>
                <div class="flex self-center justify-center w-8">
                    {% if message.read_at %}<i class="fa-solid fa-check fa-xs"></i>{% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/messages/notice_list.html
{% extends "popup.html" %}
{% load static %}
{% block style %}
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}"
          rel="stylesheet"
          type="text/css">
{% endblock style %}
{% block content %}
    <div class="h-full max-w-5xl mx-auto">
        <div class="flex justify-between w-4/5 mx-auto mb-5 xl:w-full send-msg">
            <div class="col-span-8 text-3xl font-semibold title">알림 목록</div>
            <div class="flex">
                <a href="#" onClick="location.reload();" class="block mr-8">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1"
                         stroke="currentColor"
                         class="inline w-5 h-5 text-[#373737] hover:text-neutral-400 mt-[8px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" class="mt-[8px]" />
                    </svg>
                </a>
                <a href="#" class="block" onclick="window.close();">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:text-wanted-blue mt-[6px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </a>
            </div>
        </div>
        <div class="flex justify-end w-4/5 mx-auto mb-5 text-xs xl:w-full">수신한 알림은 30일 뒤 자동 삭제됩니다.</div>
        {% for notice in notices %}
            <div class="flex my-4 max-w-[80%] mx-auto justify-center">
                <p class="px-2 mr-4 text-lg rounded-md bg-neutral-100">
                    {{ notice }} <span class="text-xs">{{ notice.created_at|date:"n/j G:i" }}</span>
                </p>
                <form class="text-red-500 hover:scale-125"
                      action="{% url "message:notice_delete" notice.id %}"
                      method="post">
                    {% csrf_token %}
                    <button type="submit">
                        <i class="fa-solid fa-delete-left"></i>
                    </button>
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/messages/read_message.html
{% extends "popup.html" %}
{% block content %}
    <div class="flex justify-center w-80% h-full max-w-5xl mx-auto">
        <div class="flex flex-col w-4/5 lg:max-w-3xl">
            <div class="text-3xl font-semibold title">메세지 확인</div>
            <div class="mt-10">
                <p class="text-2xl">보낸이</p>
                <hr class="my-2">
                <p class="indent-4">{{ message.sender }}</p>
            </div>
            <div class="mt-16">
                <p class="text-2xl">제목</p>
                <hr class="my-2">
                <p class="indent-4">{{ message.title }}</p>
            </div>
            {% if message.content %}
                <div class="mt-16">
                    <p class="text-2xl">내용</p>
                    <hr class="my-2">
                    <p class="indent-4">{{ message.content }}</p>
                </div>
            {% endif %}
            <div class="flex justify-end mt-16 message-btn">
                <a href="{% url 'message:send_message_target' message.sender.id %}"
                   class="block mr-5 message-reply hover:underline hover:text-wanted-blue"
                   title="답장하기">Reply</a>
                <form action="{% url 'message:delete_message' message.id %}"
                      method="post"
                      onsubmit="return confirm('정말 삭제하시겠습니까?');">
                    {% csrf_token %}
                    <button type="submit" class="block mr-5 message-delete" title="삭제하기">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 20 20"
                             fill="currentColor"
                             class="w-6 h-6 transition-all fill-[#373737] hover:fill-wanted-cyan">
                            <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l.3 7.5a.75.75 0 101.5-.06l.3-7.5z" clip-rule="evenodd" />
                        </svg>
                    </button>
                </form>
                <a href="{% url 'message:list_messages' %}"
                   class="block message-list"
                   title="메시지 목록">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 20 20"
                         fill="currentColor"
                         class="w-6 h-6 transition-all">
                        <path class="text-wanted-blue" fill-rule="evenodd" d="M15.988 3.012A2.25 2.25 0 0118 5.25v6.5A2.25 2.25 0 0115.75 14H13.5V7A2.5 2.5 0 0011 4.5H8.128a2.252 2.252 0 011.884-1.488A2.25 2.25 0 0112.25 1h1.5a2.25 2.25 0 012.238 2.012zM11.5 3.25a.75.75 0 01.75-.75h1.5a.75.75 0 01.75.75v.25h-3v-.25z" clip-rule="evenodd" />
                        <path class="text-wanted-green" fill-rule="evenodd" d="M2 7a1 1 0 011-1h8a1 1 0 011 1v10a1 1 0 01-1 1H3a1 1 0 01-1-1V7zm2 3.25a.75.75 0 01.75-.75h4.5a.75.75 0 010 1.5h-4.5a.75.75 0 01-.75-.75zm0 3.5a.75.75 0 01.75-.75h4.5a.75.75 0 010 1.5h-4.5a.75.75 0 01-.75-.75z" clip-rule="evenodd" />
                    </svg>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/messages/send_message_target.html
{% extends "popup.html" %}
{% block content %}
    <div class="w-full h-full max-w-5xl mx-auto">
        <div class="flex justify-between w-4/5 mx-auto xl:w-full">
            <div class="text-3xl font-semibold title">답장 보내기</div>
            <div class="flex">
                <a onclick="history.back();" href="#" class="block mr-8">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-[18px] h-[18px] hover:text-wanted-indigo mt-[8px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
                    </svg>
                </a>
                <a href="{% url 'message:list_messages' %}" class="block mr-8">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:text-wanted-green mt-[6px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                    </svg>
                </a>
                <a href="#" class="block" onclick="window.close();">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 hover:text-wanted-blue mt-[6px]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </a>
            </div>
        </div>
        <form onsubmit="send_message('{{ user.username }}','{{ receiver.id }}');"
              action="{% url "message:send_message_target" receiver.id %}"
              method="post"
              class="w-4/5 pt-4 mx-auto xl:w-full mt-7">
            <div class="text-2xl">To. {{ receiver }}</div>
            <hr class="my-4">
            {% csrf_token %}
            <input class="w-full" type="text" name="title" placeholder="Title" required>
            <hr class="my-4">
            <input class="w-full" type="text" name="content" placeholder="Content">
            <hr class="my-4">
            <div class="flex flex-row-reverse">
                <button type="submit" class="hover:underline hover:text-wanted-green">Send</button>
            </div>
        </form>
    </div>
{% endblock content %}
{% block websocket %}
    function send_message(user, receiver_id) {
    var notice = {
    "content" :  user+"(이)가 메시지를 보냈습니다.",
    "receiver_id" : receiver_id
    };
    notice_socket.send(JSON.stringify(notice));
    };
{% endblock websocket %}